#! /system/bin/sh
# Script to start "kmsg" on the device, which has a very rudimentary
# shell.
#
base=/system
export CLASSPATH=$base/framework/kmsgtracker.jar
exec app_process $base/bin com.android.commands.kmsgtracker.KmsgTracker $*

