
static pad_set tractor_default_pad_set[]=
{
//SRC
{	DDK_IOMUX_PAD_RESET_IN_B 	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_POR_B			,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_BOOT_MODE0	,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_BOOT_MODE1	,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

//TCU
{	DDK_IOMUX_PAD_TEST_MODE		,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
//CCM
{	DDK_IOMUX_PAD_PMIC_STBY_REQ	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
//SRTC
{	DDK_IOMUX_PAD_PMIC_ON_REQ	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_JTAG_MOD		,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
//ESAI-1
{	DDK_IOMUX_PAD_GPIO_8		,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
//WDOG-1
{	DDK_IOMUX_PAD_GPIO_9		,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
//goodix
{	DDK_IOMUX_PAD_PATA_CS_0 	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_NORMAL ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_PATA_CS_1 	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_NORMAL ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

#if 0
//NC
{   DDK_IOMUX_PAD_FEC_MDC  		,   DDK_IOMUX_PAD_SLEW_FAST	, 	DDK_IOMUX_PAD_DRIVE_NORMAL 	, 	DDK_IOMUX_PAD_OPENDRAIN_DISABLE,	DDK_IOMUX_PAD_PULL_UP_100K 	, 	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	, 	DDK_IOMUX_PAD_INMODE_CMOS 	, 	DDK_IOMUX_PAD_OUTVOLT_HIGH 	},
{	DDK_IOMUX_PAD_FEC_RX_ER 	,	DDK_IOMUX_PAD_SLEW_FAST ,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_FEC_TX_EN 	,	DDK_IOMUX_PAD_SLEW_FAST ,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_FEC_RXD0		,	DDK_IOMUX_PAD_SLEW_FAST ,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_FEC_TXD1		,	DDK_IOMUX_PAD_SLEW_FAST ,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_KEY_COL2		,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_PATA_DATA4	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE 	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PIN_PATA_BUFFER_EN,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_PATA_CS_0 	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_PATA_CS_1 	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_JTAG_TCK 		,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_JTAG_TMS	 	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_JTAG_TDI	 	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_JTAG_TDO	 	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_JTAG_TRSTB	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_GPIO_0		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_GPIO_2		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_GPIO_4		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_GPIO_7		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_GPIO_10		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_GPIO_11		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_GPIO_12		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_GPIO_13		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_GPIO_14		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_GPIO_18		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_GPIO_19		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_WAIT		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_BCLK		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_LBA		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_EB0		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_EB1		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_EB2		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_EB3		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_A25   	, 	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_D16   	, 	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_D17   	, 	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_D18   	, 	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_D21   	, 	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_D22   	, 	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_D23   	, 	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_DA0   	, 	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_DA2  	 	, 	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_EIM_DA10  	,   DDK_IOMUX_PAD_SLEW_SLOW	,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	  	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_EIM_DA13   	,   DDK_IOMUX_PAD_SLEW_SLOW	,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	  	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_EIM_DA14   	,   DDK_IOMUX_PAD_SLEW_SLOW	,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	 	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_EIM_DA15   	,   DDK_IOMUX_PAD_SLEW_SLOW	,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	 	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_NANDF_WE_B    ,   DDK_IOMUX_PAD_SLEW_SLOW	,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	 	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_NANDF_RE_B   	,   DDK_IOMUX_PAD_SLEW_SLOW	,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	 	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_NANDF_ALE   	,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE		,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_NANDF_CLE   	,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	 	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_NANDF_WP_B   	,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE		,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_NANDF_RB0   	,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE		,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_NANDF_CS0   	,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	 	,  	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_NANDF_CS1   	,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE		,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_CSI0_VSYNC   	,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	 	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_CSI0_PIXCLK   ,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	 	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_CSI0_MCLK   	,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	 	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_CSI0_DATA_EN  ,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	 	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
#endif

//GPIO  
{	DDK_IOMUX_PAD_KEY_ROW2		,   DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_PATA_DATA5	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_NONE 	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_PATA_DATA6	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_PATA_DATA7	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_PATA_DIOW 	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_PATA_DMACK	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_PATA_DMARQ	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_PATA_INTRQ	,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_GPIO_1		,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_GPIO_5		,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_EIM_DA1   	,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_MEDIUM ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	 	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_EIM_DA3   	,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_MEDIUM ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	  	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_EIM_DA4   	,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_MEDIUM ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	  	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_EIM_DA5   	,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_MEDIUM ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	  	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_EIM_DA6   	,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_MEDIUM ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	 	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_EIM_DA7   	,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_MEDIUM ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	 	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_EIM_DA8   	,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_MEDIUM ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	 	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_EIM_DA9   	,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_MEDIUM ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE		,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},

#ifdef CONFIG_TRACTOR_PLUS_OSV
//tractor plus osv audio mux input select, config as output gpio
{   DDK_IOMUX_PAD_CSI0_VSYNC   	,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	 	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_CSI0_PIXCLK   ,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	 	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_CSI0_MCLK   	,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	 	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_CSI0_DATA_EN  ,   DDK_IOMUX_PAD_SLEW_SLOW ,   DDK_IOMUX_PAD_DRIVE_NORMAL  ,   DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	 	,   DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,   DDK_IOMUX_PAD_INMODE_CMOS   ,   DDK_IOMUX_PAD_OUTVOLT_HIGH	},
#endif

//FLEXCAN-1
{	DDK_IOMUX_PAD_PATA_DIOR		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

//FLEXCAN-2
{	DDK_IOMUX_PAD_KEY_COL4		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_KEY_ROW4		,	DDK_IOMUX_PAD_SLEW_SLOW ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

//SPDIF
{	DDK_IOMUX_PAD_GPIO_16		,   DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_GPIO_17		,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

//ESAI-1
{	DDK_IOMUX_PAD_NANDF_CS2  	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_NANDF_CS3  	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

//AUDMUX
{	DDK_IOMUX_PAD_KEY_COL0		,   DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_KEY_ROW0		,   DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_KEY_COL1		,   DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_ENABLE	,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_KEY_ROW1		,   DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_CSI0_DAT4  	, 	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_CSI0_DAT5  	, 	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_HIGH	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_22K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_CSI0_DAT6  	, 	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_CSI0_DAT7 	, 	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_22K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

// ESAI-1
{   DDK_IOMUX_PAD_FEC_MDIO  	,   DDK_IOMUX_PAD_SLEW_FAST , 	DDK_IOMUX_PAD_DRIVE_MEDIUM , 	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K 	, 	DDK_IOMUX_PAD_HYSTERESIS_DISABLE 	, 	DDK_IOMUX_PAD_INMODE_CMOS 	, 	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_FEC_CRS_DV  	,   DDK_IOMUX_PAD_SLEW_FAST , 	DDK_IOMUX_PAD_DRIVE_MEDIUM , 	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K 	, 	DDK_IOMUX_PAD_HYSTERESIS_DISABLE 	, 	DDK_IOMUX_PAD_INMODE_CMOS 	, 	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_FEC_REF_CLK  	,   DDK_IOMUX_PAD_SLEW_FAST , 	DDK_IOMUX_PAD_DRIVE_MEDIUM , 	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K 	, 	DDK_IOMUX_PAD_HYSTERESIS_DISABLE 	, 	DDK_IOMUX_PAD_INMODE_CMOS 	, 	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_FEC_RXD1	  	,   DDK_IOMUX_PAD_SLEW_FAST , 	DDK_IOMUX_PAD_DRIVE_MEDIUM , 	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K 	, 	DDK_IOMUX_PAD_HYSTERESIS_DISABLE 	, 	DDK_IOMUX_PAD_INMODE_CMOS 	, 	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_FEC_TXD0	  	,   DDK_IOMUX_PAD_SLEW_FAST , 	DDK_IOMUX_PAD_DRIVE_MEDIUM , 	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K 	, 	DDK_IOMUX_PAD_HYSTERESIS_DISABLE 	, 	DDK_IOMUX_PAD_INMODE_CMOS 	, 	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

//ECSPI-2
{	DDK_IOMUX_PAD_EIM_OE		,	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_RW		,	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_CS0		,	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_CS1		,	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_NORMAL	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

//IPU
{	DDK_IOMUX_PAD_EIM_A16  		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH 	},
{	DDK_IOMUX_PAD_EIM_A17  		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_A18  		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_A19  		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_A20  		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_A21  		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_A22  		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_A23  		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_A24  		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_DA11 		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_DA12 		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_DI0_PIN2 		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DI0_PIN3 		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DI0_PIN4 		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DI0_PIN15 	,	DDK_IOMUX_PAD_SLEW_FAST ,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT0 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT1 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT2 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT3 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT4 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT5 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT6 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT7 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT8 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT9 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT10 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT11 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT12 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT13 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT14 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT15 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT16 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT17 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT18 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT19 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT20 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT21 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT22 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PAD_DISP0_DAT23 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_LOW	},
{	DDK_IOMUX_PIN_DI0_DISP_CLK 	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

//UART-1	
{	DDK_IOMUX_PAD_EIM_D19  		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_D20  		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_CSI0_DAT10	,   DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_CSI0_DAT11	,   DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

//UART-2
{	DDK_IOMUX_PAD_EIM_D26  		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_D27 		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_D28 		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_D29 		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
	
//UART-3	
{	DDK_IOMUX_PAD_EIM_D24  		,	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_D25  		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_D30  		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_EIM_D31  		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

//UART-4
{	DDK_IOMUX_PAD_CSI0_DAT12	,	DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_CSI0_DAT13	,   DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_CSI0_DAT16	,   DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_CSI0_DAT17	,   DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

//UART-5
{	DDK_IOMUX_PAD_CSI0_DAT14	,   DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_CSI0_DAT15	,   DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_CSI0_DAT18	,   DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_CSI0_DAT19	,   DDK_IOMUX_PAD_SLEW_SLOW	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_NONE		,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

//I2C-1
{	DDK_IOMUX_PAD_CSI0_DAT8		,   DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_ENABLE	,	DDK_IOMUX_PAD_PULL_UP_22K		,	DDK_IOMUX_PAD_HYSTERESIS_ENABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_CSI0_DAT9		,   DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_ENABLE	,	DDK_IOMUX_PAD_PULL_UP_22K		,	DDK_IOMUX_PAD_HYSTERESIS_ENABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

//I2C-2
{	DDK_IOMUX_PAD_KEY_COL3		,   DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_ENABLE	,	DDK_IOMUX_PAD_PULL_UP_22K		,	DDK_IOMUX_PAD_HYSTERESIS_ENABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_KEY_ROW3		,   DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_ENABLE	,	DDK_IOMUX_PAD_PULL_UP_22K		,	DDK_IOMUX_PAD_HYSTERESIS_ENABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

//I2C-3
{	DDK_IOMUX_PAD_GPIO_3		,	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_ENABLE	,	DDK_IOMUX_PAD_PULL_UP_22K		,	DDK_IOMUX_PAD_HYSTERESIS_ENABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_GPIO_6		,	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_ENABLE	,	DDK_IOMUX_PAD_PULL_UP_22K		,	DDK_IOMUX_PAD_HYSTERESIS_ENABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

//ESDHC1  SD1
{	DDK_IOMUX_PAD_SD1_CMD  		,	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MAX	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_ENABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_SD1_CLK  		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MAX	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_SD1_DATA0  	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MAX	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_ENABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	}, 
{	DDK_IOMUX_PAD_SD1_DATA1  	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MAX	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_ENABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_SD1_DATA2  	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MAX	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_ENABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	}, 
{	DDK_IOMUX_PAD_SD1_DATA3  	,   DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MAX ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K 	,	DDK_IOMUX_PAD_HYSTERESIS_ENABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

//ESDHC2  SD2
{	DDK_IOMUX_PAD_SD2_CMD  		,	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MAX	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_ENABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_SD2_CLK  		, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MAX	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_SD2_DATA0  	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MAX	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_ENABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	}, 
{	DDK_IOMUX_PAD_SD2_DATA1  	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MAX	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_ENABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_SD2_DATA2  	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MAX	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_ENABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	}, 
{	DDK_IOMUX_PAD_SD2_DATA3  	,   DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MAX ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_ENABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},


// ESDHC3 		
{   DDK_IOMUX_PAD_PATA_DA_0  	,	DDK_IOMUX_PAD_SLEW_FAST , 	DDK_IOMUX_PAD_DRIVE_MEDIUM 	, 	DDK_IOMUX_PAD_OPENDRAIN_DISABLE,	DDK_IOMUX_PAD_PULL_UP_22K 	, 	DDK_IOMUX_PAD_HYSTERESIS_DISABLE 	, 	DDK_IOMUX_PAD_INMODE_CMOS 	, 	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_PATA_IORDY  	,   DDK_IOMUX_PAD_SLEW_FAST , 	DDK_IOMUX_PAD_DRIVE_MEDIUM 	, 	DDK_IOMUX_PAD_OPENDRAIN_DISABLE,	DDK_IOMUX_PAD_PULL_UP_22K 	, 	DDK_IOMUX_PAD_HYSTERESIS_DISABLE 	, 	DDK_IOMUX_PAD_INMODE_CMOS 	, 	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_PATA_RESET_B  ,   DDK_IOMUX_PAD_SLEW_FAST , 	DDK_IOMUX_PAD_DRIVE_MEDIUM 	, 	DDK_IOMUX_PAD_OPENDRAIN_DISABLE,	DDK_IOMUX_PAD_PULL_UP_22K 	, 	DDK_IOMUX_PAD_HYSTERESIS_DISABLE 	, 	DDK_IOMUX_PAD_INMODE_CMOS 	, 	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_PATA_DATA8 	,   DDK_IOMUX_PAD_SLEW_FAST , 	DDK_IOMUX_PAD_DRIVE_MEDIUM 	, 	DDK_IOMUX_PAD_OPENDRAIN_DISABLE,	DDK_IOMUX_PAD_PULL_UP_22K 	, 	DDK_IOMUX_PAD_HYSTERESIS_DISABLE 	, 	DDK_IOMUX_PAD_INMODE_CMOS 	, 	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_PATA_DATA9  	,   DDK_IOMUX_PAD_SLEW_FAST , 	DDK_IOMUX_PAD_DRIVE_MEDIUM 	, 	DDK_IOMUX_PAD_OPENDRAIN_DISABLE,	DDK_IOMUX_PAD_PULL_UP_22K 	, 	DDK_IOMUX_PAD_HYSTERESIS_DISABLE 	, 	DDK_IOMUX_PAD_INMODE_CMOS 	, 	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_PATA_DATA10  	,   DDK_IOMUX_PAD_SLEW_FAST , 	DDK_IOMUX_PAD_DRIVE_MEDIUM 	, 	DDK_IOMUX_PAD_OPENDRAIN_DISABLE,	DDK_IOMUX_PAD_PULL_UP_22K 	, 	DDK_IOMUX_PAD_HYSTERESIS_DISABLE 	, 	DDK_IOMUX_PAD_INMODE_CMOS 	, 	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_PATA_DATA11  	,	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM		,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE,	DDK_IOMUX_PAD_PULL_UP_22K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE		,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_PATA_DATA0  	,   DDK_IOMUX_PAD_SLEW_FAST , 	DDK_IOMUX_PAD_DRIVE_MEDIUM 	, 	DDK_IOMUX_PAD_OPENDRAIN_DISABLE,	DDK_IOMUX_PAD_PULL_UP_22K 	, 	DDK_IOMUX_PAD_HYSTERESIS_DISABLE 	, 	DDK_IOMUX_PAD_INMODE_CMOS 	, 	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_PATA_DATA1  	,   DDK_IOMUX_PAD_SLEW_FAST , 	DDK_IOMUX_PAD_DRIVE_MEDIUM 	, 	DDK_IOMUX_PAD_OPENDRAIN_DISABLE,	DDK_IOMUX_PAD_PULL_UP_22K 	, 	DDK_IOMUX_PAD_HYSTERESIS_DISABLE 	, 	DDK_IOMUX_PAD_INMODE_CMOS 	, 	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_PATA_DATA2  	,   DDK_IOMUX_PAD_SLEW_FAST , 	DDK_IOMUX_PAD_DRIVE_MEDIUM 	, 	DDK_IOMUX_PAD_OPENDRAIN_DISABLE,	DDK_IOMUX_PAD_PULL_UP_22K 	, 	DDK_IOMUX_PAD_HYSTERESIS_DISABLE 	, 	DDK_IOMUX_PAD_INMODE_CMOS 	, 	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{   DDK_IOMUX_PAD_PATA_DATA3  	,   DDK_IOMUX_PAD_SLEW_FAST , 	DDK_IOMUX_PAD_DRIVE_MEDIUM 	, 	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_22K 	, 	DDK_IOMUX_PAD_HYSTERESIS_DISABLE 	, 	DDK_IOMUX_PAD_INMODE_CMOS 	, 	DDK_IOMUX_PAD_OUTVOLT_HIGH	},

//ESDHC4  SD4	
{	DDK_IOMUX_PAD_PATA_DA_2  	,	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_PATA_DA_1  	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_PATA_DATA12  	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	}, 
{	DDK_IOMUX_PAD_PATA_DATA13  	, 	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM	,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE ,	DDK_IOMUX_PAD_PULL_UP_100K	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_PATA_DATA14  	,	DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K 	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
{	DDK_IOMUX_PAD_PATA_DATA15  	,   DDK_IOMUX_PAD_SLEW_FAST	,	DDK_IOMUX_PAD_DRIVE_MEDIUM ,	DDK_IOMUX_PAD_OPENDRAIN_DISABLE	,	DDK_IOMUX_PAD_PULL_UP_100K 	,	DDK_IOMUX_PAD_HYSTERESIS_DISABLE	,	DDK_IOMUX_PAD_INMODE_CMOS	,	DDK_IOMUX_PAD_OUTVOLT_HIGH	},
};	
	
	
	
