static iomux_set tractor_default_mux_tab[]=
{
{	DDK_IOMUX_PIN_GPIO_19		,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	// MCU SECOND BYTE READY INTERRUPT
{	DDK_IOMUX_PIN_KEY_COL0          ,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_KEY_ROW0          ,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_KEY_COL1          ,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_KEY_ROW1          ,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_KEY_COL2          ,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_KEY_ROW2         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//MCU_INT_R
{	DDK_IOMUX_PIN_KEY_COL3         	,	DDK_IOMUX_PIN_MUXMODE_ALT4	,	DDK_IOMUX_PIN_SION_FORCE	},	//I2C_HSPD_SCK
{	DDK_IOMUX_PIN_KEY_ROW3         	,	DDK_IOMUX_PIN_MUXMODE_ALT4	,	DDK_IOMUX_PIN_SION_FORCE	},	//I2C_HSPD_SDA
{	DDK_IOMUX_PIN_KEY_COL4         	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SHOULD BE CAN, SET TO KEYPAD NOW AS NOT CONNECT
{	DDK_IOMUX_PIN_KEY_ROW4         	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SHOULD BE CAN, SET TO KEYPAD NOW AS NOT CONNECT
{	DDK_IOMUX_PIN_DI0_DISP_CLK     	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//DISP_CLK
{	DDK_IOMUX_PIN_DI0_PIN15        	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DI0_PIN2         	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DI0_PIN3         	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DI0_PIN4         	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT0       	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT1       	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT2       	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT3       	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT4       	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT5       	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT6       	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT7       	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT8       	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT9       	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT10      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT11      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT12      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT13      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT14      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT15      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT16      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT17      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT18      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT19      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT20      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT21      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT22      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_DISP0_DAT23      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_CSI0_PIXCLK      	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO CSI0_PIXCLK AS NOT CONNECT
{	DDK_IOMUX_PIN_CSI0_MCLK        	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO CSI0_MCLK AS NOT CONNECT
{	DDK_IOMUX_PIN_CSI0_DATA_EN     	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO CSI0_DATA_EN AS NOT CONNECT
{	DDK_IOMUX_PIN_CSI0_VSYNC       	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO CSI0_VSYNC AS NOT CONNECT
{	DDK_IOMUX_PIN_CSI0_DAT4        	,	DDK_IOMUX_PIN_MUXMODE_ALT5	,	DDK_IOMUX_PIN_SION_REGULAR	},	//BT_PCM_CLK
{	DDK_IOMUX_PIN_CSI0_DAT5        	,	DDK_IOMUX_PIN_MUXMODE_ALT5	,	DDK_IOMUX_PIN_SION_REGULAR	},	//BT_PCM_OUT
{	DDK_IOMUX_PIN_CSI0_DAT6        	,	DDK_IOMUX_PIN_MUXMODE_ALT5	,	DDK_IOMUX_PIN_SION_REGULAR	},	//BT_PCM_SYNC
{	DDK_IOMUX_PIN_CSI0_DAT7        	,	DDK_IOMUX_PIN_MUXMODE_ALT5	,	DDK_IOMUX_PIN_SION_REGULAR	},	//BT_PCM_IN
{	DDK_IOMUX_PIN_CSI0_DAT8        	,	DDK_IOMUX_PIN_MUXMODE_ALT5	,	DDK_IOMUX_PIN_SION_FORCE		},	//I2C_FRONT_SDA
{	DDK_IOMUX_PIN_CSI0_DAT9        	,	DDK_IOMUX_PIN_MUXMODE_ALT5	,	DDK_IOMUX_PIN_SION_FORCE		},	//I2C_FRONT_SCL
{	DDK_IOMUX_PIN_CSI0_DAT10       	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//UART1_TX(DEBUG)
{	DDK_IOMUX_PIN_CSI0_DAT11       	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//UART1_RX(DEBUG)
{	DDK_IOMUX_PIN_CSI0_DAT12       	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//UART4_TX(OBDII)
{	DDK_IOMUX_PIN_CSI0_DAT13       	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//UART4_RX(OBDII)
{	DDK_IOMUX_PIN_CSI0_DAT14       	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//UART5_TX(BLUETOOTH)
{	DDK_IOMUX_PIN_CSI0_DAT15       	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//UART5_RX(BLUETOOTH)
{	DDK_IOMUX_PIN_CSI0_DAT16       	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//UART4_RTS(OBDII)
{	DDK_IOMUX_PIN_CSI0_DAT17       	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//UART4_CTS(OBDII)
{	DDK_IOMUX_PIN_CSI0_DAT18       	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//UART5_RTS(BLUETOOTH)
{	DDK_IOMUX_PIN_CSI0_DAT19       	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//UART5_CTS(BLUETOOTH)
{	DDK_IOMUX_PIN_EIM_A25	       	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO WEIM_A[25] AS NOT CONNECT
{	DDK_IOMUX_PIN_EIM_EB2	       	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO WEIM_EB[2] AS NOT CONNECT
#ifdef CONFIG_TRACTOR_PLUS_OSV
// for OSV Hardware, we roll back these three pin for SPI use for the ISDB-T Module
{	DDK_IOMUX_PIN_EIM_D16	       	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//MCU_SPI_CLK
{	DDK_IOMUX_PIN_EIM_D17	       	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//MCU_SPI_MISO
{	DDK_IOMUX_PIN_EIM_D18         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//MCU_SPI_MOSI
#else
// for TractorPlus or Tractor Hardware, these three pin is using as GPIO to operate UDA1338
{	DDK_IOMUX_PIN_EIM_D16	       	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//MCU_SPI_CLK
{	DDK_IOMUX_PIN_EIM_D17	       	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//MCU_SPI_MISO
{	DDK_IOMUX_PIN_EIM_D18         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//MCU_SPI_MOSI
#endif
{	DDK_IOMUX_PIN_EIM_D19	       	,	DDK_IOMUX_PIN_MUXMODE_ALT6	,	DDK_IOMUX_PIN_SION_REGULAR	},	//UART1_CTS
{	DDK_IOMUX_PIN_EIM_D20        	,	DDK_IOMUX_PIN_MUXMODE_ALT6	,	DDK_IOMUX_PIN_SION_REGULAR	},	//UART1_RTS
{	DDK_IOMUX_PIN_EIM_D21         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//WEIM_D[21]
{	DDK_IOMUX_PIN_EIM_D22      	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//WEIM_D[22]
{	DDK_IOMUX_PIN_EIM_D23	        ,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//WEIM_D[23]
{	DDK_IOMUX_PIN_EIM_EB3         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//WEIM_EB[3]
{	DDK_IOMUX_PIN_EIM_D24   	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//UART3_TX(MPEG) FOR MPEG DOWNLOAD USE ALT1
{	DDK_IOMUX_PIN_EIM_D25	        ,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//UART3_RX(MPEG) FOR MPEG DOWNLOAD USE ALT1
{	DDK_IOMUX_PIN_EIM_D26      	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//UART2_TX(GPS)
{	DDK_IOMUX_PIN_EIM_D27         	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//UART2_RX(GPS)
{	DDK_IOMUX_PIN_EIM_D28         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//EIM_D28 UART2_CTS(GPS) NOT USED
{	DDK_IOMUX_PIN_EIM_D29         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//EIM_D29 UART2_RTS(GPS) NOT USED
{	DDK_IOMUX_PIN_EIM_D30      	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//UART3_CTS(MPEG)
{	DDK_IOMUX_PIN_EIM_D31         	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//UART3_RTS(MPEG)
{	DDK_IOMUX_PIN_EIM_A24         	,	DDK_IOMUX_PIN_MUXMODE_ALT3	,	DDK_IOMUX_PIN_SION_REGULAR	},	//CSI1_D19
{	DDK_IOMUX_PIN_EIM_A23         	,	DDK_IOMUX_PIN_MUXMODE_ALT3	,	DDK_IOMUX_PIN_SION_REGULAR	},	//CSI1_D18
{	DDK_IOMUX_PIN_EIM_A22      	,	DDK_IOMUX_PIN_MUXMODE_ALT3	,	DDK_IOMUX_PIN_SION_REGULAR	},	//CSI1_D17
{	DDK_IOMUX_PIN_EIM_A21         	,	DDK_IOMUX_PIN_MUXMODE_ALT3	,	DDK_IOMUX_PIN_SION_REGULAR	},	//CSI1_D16
{	DDK_IOMUX_PIN_EIM_A20         	,	DDK_IOMUX_PIN_MUXMODE_ALT3	,	DDK_IOMUX_PIN_SION_REGULAR	},	//CSI1_D15
{	DDK_IOMUX_PIN_EIM_A19         	,	DDK_IOMUX_PIN_MUXMODE_ALT3	,	DDK_IOMUX_PIN_SION_REGULAR	},	//CSI1_D14
{	DDK_IOMUX_PIN_EIM_A18         	,	DDK_IOMUX_PIN_MUXMODE_ALT3	,	DDK_IOMUX_PIN_SION_REGULAR	},	//CSI1_D13
{	DDK_IOMUX_PIN_EIM_A17         	,	DDK_IOMUX_PIN_MUXMODE_ALT3	,	DDK_IOMUX_PIN_SION_REGULAR	},	//CSI1_D12
{	DDK_IOMUX_PIN_EIM_A16         	,	DDK_IOMUX_PIN_MUXMODE_ALT3	,	DDK_IOMUX_PIN_SION_REGULAR	},	//CSI1_PIXCLK
{	DDK_IOMUX_PIN_EIM_CS0         	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//ECSPI2_SCLK -> GPIO INPUT FOR SP1 
{	DDK_IOMUX_PIN_EIM_CS1        	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//ECSPI2_MOSI -> GPIO INPUT FOR SP1
{	DDK_IOMUX_PIN_EIM_OE           	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//ECSPI2_MISO -> GPIO INPUT FOR SP1/
{	DDK_IOMUX_PIN_EIM_RW           	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//ECSPI2_SS0	 -> GPIO INPUT FOR SP1
{	DDK_IOMUX_PIN_EIM_LBA         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//WEIM_LBA
{	DDK_IOMUX_PIN_EIM_EB0         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//WEIM_EB0
{	DDK_IOMUX_PIN_EIM_EB1         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//WEIM_EB1
{	DDK_IOMUX_PIN_EIM_DA0         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//GPS_PWR_EN(GPIO)
{	DDK_IOMUX_PIN_EIM_DA1         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//GPS_RST(GPIO)
{	DDK_IOMUX_PIN_EIM_DA2         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//MCU_SPI_CSS(GPIO)
{	DDK_IOMUX_PIN_EIM_DA3         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//WIFI_RST(GPIO)
{	DDK_IOMUX_PIN_EIM_DA4         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//BT_RST(GPIO)
{	DDK_IOMUX_PIN_EIM_DA5         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//CODEC_MUTE(GPIO)
{	DDK_IOMUX_PIN_EIM_DA6         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	// Not Used
{	DDK_IOMUX_PIN_EIM_DA7         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//L3 UDA1338 (Tractor OSV)
{	DDK_IOMUX_PIN_EIM_DA8         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//L3 UDA1338 (Tractor OSV)
{	DDK_IOMUX_PIN_EIM_DA9         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//L3 UDA1338 (Tractor OSV)
{	DDK_IOMUX_PIN_EIM_DA10         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//MIC_RST(GPIO)
{	DDK_IOMUX_PIN_EIM_DA11       	,	DDK_IOMUX_PIN_MUXMODE_ALT4	,	DDK_IOMUX_PIN_SION_REGULAR	},	//CSI1_HSYNC
{	DDK_IOMUX_PIN_EIM_DA12       	,	DDK_IOMUX_PIN_MUXMODE_ALT4	,	DDK_IOMUX_PIN_SION_REGULAR	},	//CSI1_YSYNC
{	DDK_IOMUX_PIN_EIM_DA13       	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//MPEG_RST(GPIO)
{	DDK_IOMUX_PIN_EIM_DA14       	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//CSI1_RST(GPIO)
{	DDK_IOMUX_PIN_EIM_DA15       	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD1_WP(GPIO)
{	DDK_IOMUX_PIN_NANDF_WE_B  	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO NANDF_WE_B AS NOT CONNECT
{	DDK_IOMUX_PIN_NANDF_RE_B       	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO NANDF_RE_B AS NOT CONNECT
{	DDK_IOMUX_PIN_EIM_WAIT         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO EIM_WAIT AS NOT CONNECT
{	DDK_IOMUX_PIN_EIM_BCLK         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO EIM_BCLK AS NOT CONNECT
{	DDK_IOMUX_PIN_LVDS1_TX3_P      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO LVDS1_TX3_P AS NOT CONNECT
{	DDK_IOMUX_PIN_LVDS1_TX2_P      	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO LVDS1_TX2_P AS NOT CONNECT
{	DDK_IOMUX_PIN_LVDS1_CLK_P      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO LVDS1_CLK_P AS NOT CONNECT
{	DDK_IOMUX_PIN_LVDS1_TX1_P      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO LVDS1_TX1_P AS NOT CONNECT
{	DDK_IOMUX_PIN_LVDS1_TX0_P      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO LVDS1_TX0_P AS NOT CONNECT
{	DDK_IOMUX_PIN_LVDS0_TX3_P      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO LVDS0_TX3_P AS NOT CONNECT
{	DDK_IOMUX_PIN_LVDS0_CLK_P      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO LVDS0_CLK_P AS NOT CONNECT
{	DDK_IOMUX_PIN_LVDS0_TX2_P      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO LVDS0_TX2_P AS NOT CONNECT
{	DDK_IOMUX_PIN_LVDS0_TX1_P      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO LVDS0_TX1_P AS NOT CONNECT
{	DDK_IOMUX_PIN_LVDS0_TX0_P      	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO LVDS0_TX0_P AS NOT CONNECT
{	DDK_IOMUX_PIN_GPIO_10         	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO 32K_OUT AS NOT CONNECT
//{	DDK_IOMUX_PIN_GPIO_11         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//PIN DOES NOT SUPPORT CONFIGURE
//{	DDK_IOMUX_PIN_GPIO_12         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO LVDS0_TX2_P AS NOT CONNECT
//{	DDK_IOMUX_PIN_GPIO_13         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO LVDS0_TX1_P AS NOT CONNECT
//{	DDK_IOMUX_PIN_GPIO_14         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO LVDS0_TX0_P AS NOT CONNECT
{	DDK_IOMUX_PIN_NANDF_CLE        	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO NANDF_CLE  AS NOT CONNECT
{	DDK_IOMUX_PIN_NANDF_ALE        	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO NANDF_ALE AS NOT CONNECT
{	DDK_IOMUX_PIN_NANDF_WP_B       	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO NANDF_WP_B AS NOT CONNECT
{	DDK_IOMUX_PIN_NANDF_RB0        	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO NANDF_RB0 AS NOT CONNECT
{	DDK_IOMUX_PIN_NANDF_CS0        	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO NANDF_CS0 AS NOT CONNECT
{	DDK_IOMUX_PIN_NANDF_CS1        	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO GPIO6_14
{	DDK_IOMUX_PIN_NANDF_CS2        	,	DDK_IOMUX_PIN_MUXMODE_ALT3	,	DDK_IOMUX_PIN_SION_REGULAR	},	//ESAI TX0
{	DDK_IOMUX_PIN_NANDF_CS3        	,	DDK_IOMUX_PIN_MUXMODE_ALT3	,	DDK_IOMUX_PIN_SION_REGULAR	},	//ESAI TX1
{	DDK_IOMUX_PIN_FEC_MDIO         	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//ESAI SCKR
{	DDK_IOMUX_PIN_FEC_REF_CLK      	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//ESAI FSR
{	DDK_IOMUX_PIN_FEC_RX_ER        	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//GPIO1_24
{	DDK_IOMUX_PIN_FEC_CRS_DV       	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SCKT
{	DDK_IOMUX_PIN_FEC_RXD1         	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//FST
{	DDK_IOMUX_PIN_FEC_RXD0         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//GPIO1_27
{	DDK_IOMUX_PIN_FEC_TX_EN        	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//TX3_RX2
{	DDK_IOMUX_PIN_FEC_TXD1         	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//GPIO1_29
{	DDK_IOMUX_PIN_FEC_TXD0         	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//TX4_RX1
{	DDK_IOMUX_PIN_FEC_MDC         	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//GPIO1_31
{	DDK_IOMUX_PIN_PATA_DIOW        	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//BT_WAKE(GPIO)
{	DDK_IOMUX_PIN_PATA_DMACK       	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//MODEM_WAKE(GPIO)
{	DDK_IOMUX_PIN_PATA_DMARQ       	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD2_CD(GPIO)
{	DDK_IOMUX_PIN_PATA_BUFFER_EN   	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//VCTL_5V_EN(GPIO)
{	DDK_IOMUX_PIN_PATA_INTRQ       	,	DDK_IOMUX_PIN_MUXMODE_ALT4	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO INTRQ(PATA) AS NOT CONECT
{	DDK_IOMUX_PIN_PATA_DIOR        	,	DDK_IOMUX_PIN_MUXMODE_ALT4	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO DIOR(PATA) AS NOT CONECT
{	DDK_IOMUX_PIN_PATA_RESET_B     	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_PATA_IORDY       	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_PATA_DA_0        	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_PATA_DA_1        	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD4_CMD
{	DDK_IOMUX_PIN_PATA_DA_2        	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD4_CLK
{	DDK_IOMUX_PIN_PATA_CS_0        	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_PATA_CS_1           	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_PATA_DATA0           	,	DDK_IOMUX_PIN_MUXMODE_ALT4	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_PATA_DATA1           	,	DDK_IOMUX_PIN_MUXMODE_ALT4	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_PATA_DATA2           	,	DDK_IOMUX_PIN_MUXMODE_ALT4	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_PATA_DATA3           	,	DDK_IOMUX_PIN_MUXMODE_ALT4	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD3_DATA7
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_PATA_DATA4           	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO PATA_DATA[4] AS NOT CONNECT
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_PATA_DATA5           	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//PMIC_INT(GPIO)
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_PATA_DATA6           	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//WIFI_WAKEUP(GPIO)
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_PATA_DATA7           	,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD1_CD 
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_PATA_DATA8           	,	DDK_IOMUX_PIN_MUXMODE_ALT4	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_PATA_DATA9           	,	DDK_IOMUX_PIN_MUXMODE_ALT4	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_PATA_DATA10           	,	DDK_IOMUX_PIN_MUXMODE_ALT4	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_PATA_DATA11           	,	DDK_IOMUX_PIN_MUXMODE_ALT4	,	DDK_IOMUX_PIN_SION_REGULAR	},
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_PATA_DATA12           	,	DDK_IOMUX_PIN_MUXMODE_ALT4	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD2_DAT4
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_PATA_DATA13           	,	DDK_IOMUX_PIN_MUXMODE_ALT4	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD2_DAT1
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_PATA_DATA14           	,	DDK_IOMUX_PIN_MUXMODE_ALT4	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD4_DATA2
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_PATA_DATA15           	,	DDK_IOMUX_PIN_MUXMODE_ALT4	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD2-DAT3
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_SD1_DATA0           	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD1_DATA0
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_SD1_DATA1           	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD1_DATA1
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_SD1_CMD       	    	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD1_CMD   
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_SD1_DATA2           	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD1_DATA2  
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_SD1_CLK           		,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD1_CLK
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_SD1_DATA3       	   	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD1_DATA3 
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_SD2_CLK           		,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD2_CLK 
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_SD2_CMD           		,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD2_CMD
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_SD2_DATA3           	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD2_DATA3
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_SD2_DATA2           	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD2_DATA2
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_SD2_DATA1           	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD2_DATA1
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_SD2_DATA0           	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SD2_DATA0
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_GPIO_0		        ,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//CCM_SSI_EXT1_CLK
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_GPIO_1           		,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SYSTEM_DOWN
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_GPIO_9           		,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//WDT_OUTPUT
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_GPIO_3           		,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_FORCE	},	//I2C_MB_CLK
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_GPIO_6       	    	,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_FORCE	},	//I2C_MB_SDA   
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_GPIO_2           		,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//GPIO_2  
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_GPIO_4           		,	DDK_IOMUX_PIN_MUXMODE_ALT2	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO COL[7] AS NOT CONNNECT
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_GPIO_5       	   	,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//ESAI TX2_RX3
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_GPIO_7           		,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//PCLOCK 
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_GPIO_8           		,	DDK_IOMUX_PIN_MUXMODE_ALT0	,	DDK_IOMUX_PIN_SION_REGULAR	},	//ESAI TX5_RX0
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_GPIO_16           		,	DDK_IOMUX_PIN_MUXMODE_ALT5	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SPDIF_RX
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_GPIO_17           		,	DDK_IOMUX_PIN_MUXMODE_ALT5	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SPDIF_TX
{	DDK_IOMUX_PIN_SW_MUX_CTL_PAD_GPIO_18           		,	DDK_IOMUX_PIN_MUXMODE_ALT1	,	DDK_IOMUX_PIN_SION_REGULAR	},	//SET TO ONEWIRE AS NOT CONNECT
};


