static selectmux_set tractor_default_select_set[]={
{DDK_IOMUX_AUDMUX_P4_INPUT_DA_AMX_SELECT_INPUT, 				INPUT_CTL_PATH0},	//SET TO DISP0_DAT23 AS NOT USED
{DDK_IOMUX_AUDMUX_P4_INPUT_DB_AMX_SELECT_INPUT,				INPUT_CTL_PATH0},	//SET TO DISP0_DAT21 AS NOT USED
{DDK_IOMUX_AUDMUX_P4_INPUT_RXCLK_AMX_SELECT_INPUT,			INPUT_CTL_PATH0},	//SET TO DISP0_DAT19 AS NOT USED
{DDK_IOMUX_AUDMUX_P4_INPUT_RXFS_AMX_SELECT_INPUT,			INPUT_CTL_PATH0},	//SET TO DISP0_DAT18 AS NOT USED
{DDK_IOMUX_AUDMUX_P4_INPUT_TXCLK_AMX_SELECT_INPUT ,			INPUT_CTL_PATH0},	//SET TO DISP0_DAT20 AS NOT USED
{DDK_IOMUX_AUDMUX_P4_INPUT_TXFS_AMX_SELECT_INPUT,			INPUT_CTL_PATH0},	//SET TO DISP0_DAT22 AS NOT USED
{DDK_IOMUX_AUDMUX_P5_INPUT_DA_AMX_SELECT_INPUT,				INPUT_CTL_PATH0},	//SET TO KEY_ROW1 AS I2S_DIN
{DDK_IOMUX_AUDMUX_P5_INPUT_DB_AMX_SELECT_INPUT,				INPUT_CTL_PATH0},	//KEY_ROW0 FOR ALT2 I2S_DOUT
{DDK_IOMUX_AUDMUX_P5_INPUT_RXCLK_AMX_SELECT_INPUT,			INPUT_CTL_PATH0},	//SET TO DISP0_DAT14 AS NOT USED
{DDK_IOMUX_AUDMUX_P5_INPUT_RXFS_AMX_SELECT_INPUT,			INPUT_CTL_PATH0},	//SET TO DISP0_DAT13 AS NOT USED
{DDK_IOMUX_AUDMUX_P5_INPUT_TXCLK_AMX_SELECT_INPUT,			INPUT_CTL_PATH0},	//KEY_COL0 FOR ALT2 I2S_SCLK
{DDK_IOMUX_AUDMUX_P5_INPUT_TXFS_AMX_SELECT_INPUT,			INPUT_CTL_PATH0},	//KEY_COL1 FOR ALT2 I2S_LRCLK
{DDK_IOMUX_CAN1_IPP_IND_CANRX_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO KEY_ROW2 AS NOT USED
{DDK_IOMUX_CAN2_IPP_IND_CANRX_SELECT_INPUT,					INPUT_CTL_PATH0},	//KEY_ROW4 ALT2 CAN2
{DDK_IOMUX_CCM_IPP_ASRC_EXT_SELECT_INPUT,						INPUT_CTL_PATH1},	//SET TO GPIO_18 AS NOT USED
{DDK_IOMUX_CCM_IPP_DI1_CLK_SELECT_INPUT,						INPUT_CTL_PATH0},	//SET TO EIM_EB2 AS NOT USED
{DDK_IOMUX_CCM_PLL1_BYPASS_CLK_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO SD1_CMD AS NOT USED
{DDK_IOMUX_CCM_PLL2_BYPASS_CLK_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO SD1_DATA2 AS NOT USED
{DDK_IOMUX_CCM_PLL3_BYPASS_CLK_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO SD1_DATA0 AS NOT USED
{DDK_IOMUX_CCM_PLL4_BYPASS_CLK_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO KEY_ROW3 AS NOT USED
{DDK_IOMUX_CSPI_IPP_CSPI_CLK_IN_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO DISP0_DAT0 AS NOT USED
{DDK_IOMUX_CSPI_IPP_IND_MISO_SELECT_INPUT,						INPUT_CTL_PATH0},	//SET TO DISP0_DAT2 AS NOT USED
{DDK_IOMUX_CSPI_IPP_IND_MOSI_SELECT_INPUT,						INPUT_CTL_PATH0},	//SET TO DISP0_DAT1 AS NOT USED
{DDK_IOMUX_CSPI_IPP_IND_SS0_B_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO DISP0_DAT3 AS NOT USED
{DDK_IOMUX_CSPI_IPP_IND_SS1_B_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO DISP0_DAT4 AS NOT USED
{DDK_IOMUX_CSPI_IPP_IND_SS2_B_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO DISP0_DAT5 AS NOT USED
{DDK_IOMUX_CSPI_IPP_IND_SS3_B_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO DISP0_DAT6 AS NOT USED
{DDK_IOMUX_ECSPI1_IPP_CSPI_CLK_IN_SELECT_INPUT,				INPUT_CTL_PATH3},	//SET TO MCU_ECSPI_CLK
{DDK_IOMUX_ECSPI1_IPP_IND_MISO_SELECT_INPUT,					INPUT_CTL_PATH3},	//SET TO MCU_ECSPI_MISO
{DDK_IOMUX_ECSPI1_IPP_IND_MOSI_SELECT_INPUT,					INPUT_CTL_PATH3},	//SET TO MCU_ECSPI_MOSI
{DDK_IOMUX_ECSPI1_IPP_IND_SS_B_0_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO KEY_ROW1 AS NOT USED
{DDK_IOMUX_ECSPI1_IPP_IND_SS_B_1_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO KEY_COL2 AS NOT USED
{DDK_IOMUX_ECSPI1_IPP_IND_SS_B_2_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO KEY_ROW2 AS NOT USED
{DDK_IOMUX_ECSPI1_IPP_IND_SS_B_3_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO KEY_COL3 AS NOT USED
{DDK_IOMUX_ECSPI2_IPP_CSPI_CLK_IN_SELECT_INPUT,				INPUT_CTL_PATH2},	//ECSPI2_SCLK -> SET TO DISP0_DAT19 AS NOT USED
{DDK_IOMUX_ECSPI2_IPP_IND_MISO_SELECT_INPUT,					INPUT_CTL_PATH2},	//ECSPI2_MISO -> SET TO DISP0_DAT17 AS NOT USED
{DDK_IOMUX_ECSPI2_IPP_IND_MOSI_SELECT_INPUT,					INPUT_CTL_PATH2},	//ECSPI2_MOSI	 -> SET TO DISP0_DAT16 AS NOT USED				
{DDK_IOMUX_ECSPI2_IPP_IND_SS_B_0_SELECT_INPUT,					INPUT_CTL_PATH2},	//ECSPI2_SS0   -> SET TO DISP0_DAT18 AS NOT USED
{DDK_IOMUX_ECSPI2_IPP_IND_SS_B_1_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO DISP_DAT15 AS NOT USED
{DDK_IOMUX_ESAI1_IPP_IND_FSR_SELECT_INPUT,						INPUT_CTL_PATH0},	//ESAI FSR
{DDK_IOMUX_ESAI1_IPP_IND_FST_SELECT_INPUT,						INPUT_CTL_PATH0},	//ESAI FST
{DDK_IOMUX_ESAI1_IPP_IND_HCKR_SELECT_INPUT,					INPUT_CTL_PATH0},	//ESAI RX FR
{DDK_IOMUX_ESAI1_IPP_IND_HCKT_SELECT_INPUT,					INPUT_CTL_PATH0},	//ESAI RX D0
{DDK_IOMUX_ESAI1_IPP_IND_SCKR_SELECT_INPUT,					INPUT_CTL_PATH0},	//ESAI SCKR
{DDK_IOMUX_ESAI1_IPP_IND_SCKT_SELECT_INPUT,					INPUT_CTL_PATH0},	//ESAI SCKT
{DDK_IOMUX_ESAI1_IPP_IND_SDO0_SELECT_INPUT,					INPUT_CTL_PATH0},	//ESAI TX0
{DDK_IOMUX_ESAI1_IPP_IND_SDO1_SELECT_INPUT,					INPUT_CTL_PATH0},	//ESAI TX1
{DDK_IOMUX_ESAI1_IPP_IND_SDO2_SDI3_SELECT_INPUT,				INPUT_CTL_PATH0},	//ESAI TXD1
{DDK_IOMUX_ESAI1_IPP_IND_SDO3_SDI2_SELECT_INPUT,				INPUT_CTL_PATH0},	//ESAI TX3 RX2
{DDK_IOMUX_ESAI1_IPP_IND_SDO4_SDI1_SELECT_INPUT,				INPUT_CTL_PATH0},	//ESAI TX4 RX1
{DDK_IOMUX_ESAI1_IPP_IND_SDO5_SDI0_SELECT_INPUT,				INPUT_CTL_PATH0},	//ESAI MDC
{DDK_IOMUX_ESDHC1_IPP_WP_ON_SELECT_INPUT,						INPUT_CTL_PATH0},	//SET TO DI0_PIN4 AS NOT USED
{DDK_IOMUX_FEC_FEC_COL_SELECT_INPUT,							INPUT_CTL_PATH0},	//SET TO KEY_ROW1 AS NOT USED
{DDK_IOMUX_FEC_FEC_MDI_SELECT_INPUT,							INPUT_CTL_PATH0},	//SET TO KEY_COL2 AS NOT USED
{DDK_IOMUX_FEC_FEC_RX_CLK_SELECT_INPUT,						INPUT_CTL_PATH0},	//SET TO KEY_COL1 AS NOT USED
{DDK_IOMUX_FIRI_IPP_IND_RXD_SELECT_INPUT,						INPUT_CTL_PATH0},	//SET TO EIM_D26 AS NOT USED
{DDK_IOMUX_GPC_PMIC_RDY_SELECT_INPUT,							INPUT_CTL_PATH0},	//SET TO EIM_EB0 AS NOT USED
{DDK_IOMUX_I2C1_IPP_SCL_IN_SELECT_INPUT,						INPUT_CTL_PATH0},	//I2C_FRONT_SCK
{DDK_IOMUX_I2C1_IPP_SDA_IN_SELECT_INPUT,						INPUT_CTL_PATH0},	//I2C_FRONT_SDA
{DDK_IOMUX_I2C2_IPP_SCL_IN_SELECT_INPUT,						INPUT_CTL_PATH0},	//I2C_HSPD_SDA
{DDK_IOMUX_I2C2_IPP_SDA_IN_SELECT_INPUT,						INPUT_CTL_PATH0},	//I2C_HSPD_SCL
{DDK_IOMUX_I2C3_IPP_SCL_IN_SELECT_INPUT,						INPUT_CTL_PATH1},	//I2C_MB_SCL
{DDK_IOMUX_I2C3_IPP_SDA_IN_SELECT_INPUT,						INPUT_CTL_PATH1},	//I2C_MB_SDA
{DDK_IOMUX_IPU_IPP_DI_0_IND_DISPB_SD_D_SELECT_INPUT,			INPUT_CTL_PATH0},	//SET TO EIM_D22 AS NOT USED
{DDK_IOMUX_IPU_IPP_DI_1_IND_DISPB_SD_D_SELECT_INPUT,			INPUT_CTL_PATH0},	//SET TO EIM_D17 AS NOT USED
{DDK_IOMUX_IPU_IPP_IND_SENS1_DATA_EN_SELECT_INPUT,			INPUT_CTL_PATH0},	//SET TO EIM_D23 AS NOT USED
{DDK_IOMUX_IPU_IPP_IND_SENS1_HSYNC_SELECT_INPUT,				INPUT_CTL_PATH1},	//CSI1_HSYNC
{DDK_IOMUX_IPU_IPP_IND_SENS1_VSYNC_SELECT_INPUT,				INPUT_CTL_PATH1},	//CSI1_VSYNC
{DDK_IOMUX_KPP_IPP_IND_COL_5_SELECT_INPUT,						INPUT_CTL_PATH0},	//SET TO GPIO_19 AS NOT USED
{DDK_IOMUX_KPP_IPP_IND_COL_6_SELECT_INPUT,						INPUT_CTL_PATH0},	//SET TO CSI0_DAT6 AS NOT USED
{DDK_IOMUX_KPP_IPP_IND_COL_7_SELECT_INPUT,						INPUT_CTL_PATH0},	//SET TO CSI0_DAT8 AS NOT USED
{DDK_IOMUX_KPP_IPP_IND_ROW_5_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO CSI0_DAT5 AS NOT USED
{DDK_IOMUX_KPP_IPP_IND_ROW_6_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO CSI0_DAT7 AS NOT USED
{DDK_IOMUX_KPP_IPP_IND_ROW_7_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO CSI0_DAT9 AS NOT USED
{DDK_IOMUX_MLB_MLBCLK_IN_SELECT_INPUT,							INPUT_CTL_PATH0},	//NANDF_CS1
{DDK_IOMUX_MLB_MLBDAT_IN_SELECT_INPUT,						INPUT_CTL_PATH2},	//GPIO_2
{DDK_IOMUX_MLB_MLBSIG_IN_SELECT_INPUT,							INPUT_CTL_PATH0},	//SET TO NANDF_CS2 AS NOT USED
{DDK_IOMUX_OWIRE_BATTERY_LINE_IN_SELECT_INPUT,					INPUT_CTL_PATH0},	//SET TO PATA_DA_0 AS NOT USED
{DDK_IOMUX_SDMA_EVENTS_14_SELECT_INPUT,						INPUT_CTL_PATH0},	//SET TO DISP0_DAT16 AS NOT USED
{DDK_IOMUX_SDMA_EVENTS_15_SELECT_INPUT,						INPUT_CTL_PATH0},	//SET TO DISP0_DAT17 AS NOT USED						
{DDK_IOMUX_SPDIF_SPDIF_IN1_SELECT_INPUT,						INPUT_CTL_PATH1},	//SPDIF_RX
{DDK_IOMUX_UART1_IPP_UART_RTS_B_SELECT_INPUT,					INPUT_CTL_PATH1},	//EIM_D20
{DDK_IOMUX_UART1_IPP_UART_RXD_MUX_SELECT_INPUT,				INPUT_CTL_PATH1},	//CSI0_DAT11
{DDK_IOMUX_UART2_IPP_UART_RTS_B_SELECT_INPUT, 					INPUT_CTL_PATH1},	//EIM_D29
{DDK_IOMUX_UART2_IPP_UART_RXD_MUX_SELECT_INPUT, 				INPUT_CTL_PATH1}, 	//EIM_D27
{DDK_IOMUX_UART3_IPP_UART_RTS_B_SELECT_INPUT,					INPUT_CTL_PATH3},	//EIM_D31
{DDK_IOMUX_UART3_IPP_UART_RXD_MUX_SELECT_INPUT,				INPUT_CTL_PATH1},	//EIM_D25
{DDK_IOMUX_UART4_IPP_UART_RTS_B_SELECT_INPUT,					INPUT_CTL_PATH0},	//CSI0_DAT16
{DDK_IOMUX_UART4_IPP_UART_RXD_MUX_SELECT_INPUT,				INPUT_CTL_PATH3},	//CSI0_DAT13
{DDK_IOMUX_UART5_IPP_UART_RTS_B_SELECT_INPUT,					INPUT_CTL_PATH2},	//CSI0_DAT18
{DDK_IOMUX_UART5_IPP_UART_RXD_MUX_SELECT_INPUT,				INPUT_CTL_PATH3},	//CSI0_DAT15
{DDK_IOMUX_USBOH3_IPP_IND_OTG_OC_SELECT_INPUT,				INPUT_CTL_PATH0},	//SET TO KEY_COL4 AS NOT USED
{DDK_IOMUX_USBOH3_IPP_IND_UH1_OC_SELECT_INPUT,				INPUT_CTL_PATH0},	//SET TO EIM_D30 AS NOT USED
{DDK_IOMUX_USBOH3_IPP_IND_UH2_OC_SELECT_INPUT,				INPUT_CTL_PATH0},	//SET TO EIM_D19 AS NOT USED
};


